security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
spring:
  security:
    user:
      name: user
      password: 123
  datasource:
    driver-class-name: org.postgresql.Driver
    username: upchuck_user
    url: jdbc:postgresql://localhost:5432/upchuckdb
    password: upchuck
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crm

